### ISSUE TITLE
Yandex Mobile Ads by osov

### ISSUE THREAD

**Issue by astrochili** [astrochili/awesome-defold#1]
Don't undestand the key difference between these repositories:

- [Yandex Easy Monetezation](https://github.com/osov/defold-yandex-easy-monetization) — Yandex Mobile Ads SDK on Android.
- [Yandex Mobile Ads](https://github.com/osov/defold-yandex-sdk-ads) — Yandex Mobile Ads SDK on Android.

Explanation from the author is needed before adding.

**Comment by astrochili** [comment]
@osov Hi! Could you please help sort this out?

**Comment by osov** [comment]
[Yandex Easy Monetezation](https://github.com/osov/defold-yandex-easy-monetization) - Mediation from Yandex
[Yandex Mobile Ads](https://github.com/osov/defold-yandex-sdk-ads) - Only yandex network

**Comment by astrochili** [comment]
Thanks, alredy added 👌
