### ISSUE TITLE
Text-Based Defold Tutorials

### ISSUE THREAD

**Issue by whiteboxdev** [astrochili/awesome-defold#10]
Hi there, I started a repository for text-based Defold tutorials: https://github.com/klaytonkowalski/tutorial-defold/tree/main

I'm not sure if this kind of repository belongs in `awesome-defold`, but if it does, then I would appreciate if it could be added. Some of the tutorials will provide functional Defold projects that can be downloaded, launched, and analyzed.

**Comment by astrochili** [comment]
Thanks! I wish you success in creating new tutorials, I like such tutorials more than videos.
