### ISSUE TITLE
Ahash and AURL do more work then required

### ISSUE THREAD

**Issue by monkoose** [astrochili/awesome-defold#17]
Even though they cache hash() value, they are still checking key existence every time.
Maybe consider to remove them from this list or adding some comment?

Correct code for ahash module should be something like
```lua
return setmetatable({}, {
    __index = function(t, k)
        rawset(t, k, hash(k))
        return t[k]
    end,
})
```
And a similar for AURL.

**Comment by monkoose** [comment]
Actually, I have found that author is still some kinda active on github.
I should create a PR on their repositories.
I will close this after Ahash author's reply.

**Comment by astrochili** [comment]
I think I have to close this issue because this repository is a list but not the place to solve issues of certain libraries. Please create issues in the correspond repositories, here is no sence to expect answers from authors.
