### ISSUE TITLE
Libraries by subsoap

### ISSUE THREAD

**Issue by astrochili** [astrochili/awesome-defold#2]
There is no assurance that these libraries are fully working and intended for use, because there are no docs for them. Confirmation of the author is required.

- [XP](https://github.com/subsoap/xp) — A generic leveling up system.
- [Vita](https://github.com/subsoap/xp) — Auto-regenerating health / heart / life / energy type of system for accessing content.
- [SoundBank](https://github.com/subsoap/soundbank) — Easily play sounds and music playlists.
- [WrapText](https://github.com/subsoap/wraptext) — The line breaking rules in East Asian languages wrapper.
- [DefRS](https://github.com/subsoap/defrs) — A collection of useful general resources.

**Comment by astrochili** [comment]
@subsoap Hi! Could you please help sort this out?

**Comment by subsoap** [comment]
Sorry I didn't see this before! It said supsoap instead of subsoap so maybe that's why I never clicked it. 🤷

**Comment by astrochili** [comment]
Ah, sorry, typo in the title ) Added all where there were examples of use.
