### ISSUE TITLE
Add awesome-defold to sindresorhus/awesome

### ISSUE THREAD

**Issue by neonlifes** [astrochili/awesome-defold#6]
How about adding awesome-defold to [this](https://github.com/sindresorhus/awesome#gaming) list?

**Comment by astrochili** [comment]
Some day someone will add it, I think. But I would suggest waiting to see if this list survives or not first 😁.

**Comment by astrochili** [comment]
Ouch, just noticed. As long as this list is involved in politics, there is no aspiration to get there.
